version: '3'

services:
  backend:
    build: './src/backend'
    ports:
      - '8080:80'
    volumes:
      - './src/backend:/app'
  frontend:
    build: './src/frontend'
    ports:
      - '80:80'
    volumes:
      - './src/frontend/html:/usr/share/nginx/html'
