version: '3'

services:
  database:
    build: ./src/database
    ports:
      - 5432:5432
    volumes:
      - ./src/database:/docker-entrypoint-initdb.d
  backend:
    build: ./src/backend
    ports:
      - 8080:80
    volumes:
      - ./src/backend:/app
  frontend:
    build: ./src/frontend
    ports:
      - 9090:80
    volumes:
      - ./src/frontend/public:/usr/local/apache2/htdocs/
